force-app/main/default/objects/Analytics_Subscribe__e/Analytics_Subscribe__e.object-meta.xml
<CustomObject>
    <description>A an event that allows the end user to subscribe to a specific dashboard to have emails sent to them.</description>
    <label>Analytics Subscribe</label>
    <pluralLabel>Analytics Subscribe</pluralLabel>
</CustomObject>

force-app/main/default/objects/Analytics_Subscribe__e/fields/Dashboard_Name__c.field-meta.xml
<CustomField>
    <fullName>Dashboard_Name__c</fullName>
    <label>Dashboard Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WaveEmailSubscriptionsController.cls
public class WaveEmailSubscriptionsController {
    public class DashboardOrLens{
        @AuraEnabled public String theId {get; set;}
        @AuraEnabled public String theName {get; set;}
        @AuraEnabled public String folderName {get; set;}
        @AuraEnabled public String iconName {get; set;}
        @AuraEnabled public String lastModifiedDate {get; set;}
        public DashboardOrLens(String theId,String dbName,String folderName,String lastModifiedDate,String iconName){
            this.theId=theId;
            this.theName=dbName;
            this.folderName=folderName;
            this.lastModifiedDate=lastModifiedDate;
            this.iconName=iconName;
        }
    }
    @AuraEnabled
    public static void sendEmailDashboardRequest(String dbOrLensName){
        Analytics_Subscribe__e theEvent = new Analytics_Subscribe__e(Dashboard_Name__c=dbOrLensName);
        EventBus.publish(theEvent);
    }
    @AuraEnabled
    public static List<DashboardOrLens> getDashboardAndLensList(){
        List<DashboardOrLens> result = new List<DashboardOrLens>();
        for(EADashboardResponseParser.Dashboards db:WaveUtils.getDashboardList()){
            result.add(new DashboardOrLens(db.id,db.label,db.folder.label,db.lastModifiedDate,'standard:dashboard'));
        }
        for(EALensResponseParser.Lenses lens:WaveUtils.getLensList()){
            result.add(new DashboardOrLens(lens.id,lens.label,lens.folder.label,lens.lastModifiedDate,'utility:chart'));
        }
        return result;
    }    
}